title: "Maryna Aumayr · Portfolio"
description: >
 from CV and wet-lab methods to bio/data projects — bridging science, tech, and communication with purpose.
baseurl: "" 
url: "https://dkMarina.github.io"

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed
  
header_pages:
  - index.md
  - cv.md
  - skills.md
  - projects.md

